# ==========================================
# 🛡️ InazumaKV Master 节点 (极致计算型)
# ==========================================
# --- System ---
role = master
port = 6379
log_level = warn

# Master 仅开启 AOF 追加，通过 io_uring 落盘，不做 RDB
persistence_mode = aof

# --- Persistence Path ---
aof_path = data/kvs.aof
rdb_path = data/kvs.rdb

# --- Disaster Recovery (AOF Rewrite & BGSAVE) ---
# [对齐项] 强行关闭自动重写，把磁盘带宽100%让给业务。由外部脚本在凌晨手动触发 BGREWRITEAOF
aof_rewrite_percentage = 0

# Master 追求极致计算性能，彻底关闭 RDB 定时快照 (交由 Slave 负责)
save_interval_ms = 0
save_changes_limit = 0

# --- AF_XDP (Kernel Bypass Sender) ---
# ifname = eth_xdp
ifname = ""
# Master 必须知道底层网络帧要把数据克隆发给谁 (XDP 零拷贝链路)
slave_ip = 192.168.124.14
slave_mac = 00:0c:29:2c:bc:bf