# ==========================================
# 🛡️ InazumaKV Slave 节点 (容灾备份型)
# ==========================================
# --- System ---
role = slave
port = 6380
log_level = info

# [修正] 既然是真正的灾备中心，开启 RDB 内存快照模式
persistence_mode = rdb

# --- Persistence Path ---
aof_path = data/kvs.aof
rdb_path = data/kvs.rdb

# --- Disaster Recovery (AOF Rewrite & BGSAVE) ---
# [对齐项] 即使当前是 RDB 模式，也把 AOF 重写项配上兜底，保持主从配置文件结构 100% 一致
aof_rewrite_percentage = 0

# [修正] 真正激活注释里的逻辑：60秒 (60000ms) 内如果有 100000 次修改，则无锁写磁盘 (BGSAVE)
save_interval_ms = 60000
save_changes_limit = 100000

# --- Replication (TCP Sync Fallback) ---
# Slave 启动时需要通过 TCP 找 Master 拉取旧数据进行全量同步，以及用作 PSYNC 兜底通道
master_ip = 192.168.124.13
master_port = 6379

# --- AF_XDP (Kernel Bypass Receiver) ---
ifname = eth_xdp
# ifname = ""